version: "3.8"

services: 
  app:
    container_name: service
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    ports: 
      - 3000:3000
    volumes: 
      - .:/app
      - '/app/node_modules'
    depends_on: 
      - mysql_server
    networks:
      - dev_network
  
  # MySQL
  mysql_server:
    image: mysql:latest
    container_name: mysql
    volumes:
      - ./database:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin@2021
    networks:
      - dev_network
    
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - mysql_server
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: mysql_server
      MYSQL_ROOT_PASSWORD: admin@2021 
    networks:
      - dev_network

networks:
  dev_network:

    